### ISSUE TITLE
gensim2.py is missing

### ISSUE THREAD

**Issue by abcteo** [dansoutner/LSTMLM#1]

**Comment by dansoutner** [comment]
_gensim2_ is a modified gensim package with online word2vec functionality. You could obtain it from https://github.com/rutum/gensim. Info about it is in http://rutumulkar.com/blog/2015/word2vec/. I will add this to repo soon.

**Comment by abcteo** [comment]
hi, yes I can install gensim from https://github.com/rutum/gensim, but i believe you modified it to gensim2, which is different from gensim. please help to add to the repo. thanks

**Comment by dansoutner** [comment]
The repo is added.
