### ISSUE TITLE
lstmlm.py: error: unrecognized arguments: --load-net exampleh1000.lstm-lm.13.lstm

### ISSUE THREAD

**Issue by abcteo** [dansoutner/LSTMLM#2]
try to evaluate, then encounter this err, pls help
 python lstmlm.py --load-net exampleh1000.lstm-lm.13.lstm --ppl valid.txt --ngram ngram.model.arpa 0.2

**Comment by dansoutner** [comment]
Hi, 
not a big deal: there is an old argument in _README.md_.
The correct argument for loading NNet is **--initmodel** or **-m**.

**Comment by abcteo** [comment]
thanks for the prompt repy,
what would be the correct argument for --wip and  --lmw please, these are not working also
Thanks again

**Comment by dansoutner** [comment]
Also corrected in README.md: there are no such these arguments at the time, rescoring outputs only score for every line of input file and you must further operate with this output.

Regards

Daniel

**Comment by abcteo** [comment]
Perfect. Thanks again for the prompt reply
BTW, would it be possible to share the paper please? As I would like to understand better the algorithm

Thanks a lot

**Comment by dansoutner** [comment]
Some of my papers are on my profile here:
http://www.kky.zcu.cz/en/people/soutner-daniel

**Comment by abcteo** [comment]
Great. I found the paper. Thank you
